const FPS = 60;
const UPDATE_RATE = 1000 / FPS;

const REST_RATE = 0.05;
const CUSTOMER_RATE = 0.02;
const WIDGET_PRICE = 10;
const SALE_RATE = 0.01;
const SILICON_PRICE = 5;
const CUSTOMER_MAX = 100;
const DEFAULT_CUSTOMER_PATIENCE = 80;
const PATIENCE_LOSS_RATE = 0.02;
